cliArgs:
  geometry: true
  planmode: false
  threads: 4
  explore: 5
  limit: '10mb'
  logdir: '/..'
  logsize: '100M'
  maxlocations: 5000
  maxvehicles: 200
  override: true
  path: ''
  port: 3000
  router: 'osrm'
  timeout: 300000
  baseurl: '/'
routingServers:
  osrm:
    car:
      host: 'osrm-backend'
      port: '5000'
